//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./user_types');
//HELPER FUNCTIONS AND STRUCTURES

var UserAccountService_getAccounts_args = function(args) {
};
UserAccountService_getAccounts_args.prototype = {};
UserAccountService_getAccounts_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UserAccountService_getAccounts_args.prototype.write = function(output) {
  output.writeStructBegin('UserAccountService_getAccounts_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UserAccountService_getAccounts_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [ttypes.UserAccount]);
    }
  }
};
UserAccountService_getAccounts_result.prototype = {};
UserAccountService_getAccounts_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new ttypes.UserAccount();
          elem6.read(input);
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UserAccountService_getAccounts_result.prototype.write = function(output) {
  output.writeStructBegin('UserAccountService_getAccounts_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        iter7.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UserAccountService_insertAccounts_args = function(args) {
  this.userAccount = null;
  if (args) {
    if (args.userAccount !== undefined && args.userAccount !== null) {
      this.userAccount = new ttypes.UserAccount(args.userAccount);
    }
  }
};
UserAccountService_insertAccounts_args.prototype = {};
UserAccountService_insertAccounts_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.userAccount = new ttypes.UserAccount();
        this.userAccount.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UserAccountService_insertAccounts_args.prototype.write = function(output) {
  output.writeStructBegin('UserAccountService_insertAccounts_args');
  if (this.userAccount !== null && this.userAccount !== undefined) {
    output.writeFieldBegin('userAccount', Thrift.Type.STRUCT, 1);
    this.userAccount.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UserAccountService_insertAccounts_result = function(args) {
};
UserAccountService_insertAccounts_result.prototype = {};
UserAccountService_insertAccounts_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UserAccountService_insertAccounts_result.prototype.write = function(output) {
  output.writeStructBegin('UserAccountService_insertAccounts_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UserAccountServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
UserAccountServiceClient.prototype = {};
UserAccountServiceClient.prototype.seqid = function() { return this._seqid; };
UserAccountServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };
UserAccountServiceClient.prototype.getAccounts = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getAccounts();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getAccounts();
  }
};

UserAccountServiceClient.prototype.send_getAccounts = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getAccounts', Thrift.MessageType.CALL, this.seqid());
  var args = new UserAccountService_getAccounts_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

UserAccountServiceClient.prototype.recv_getAccounts = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new UserAccountService_getAccounts_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getAccounts failed: unknown result');
};
UserAccountServiceClient.prototype.insertAccounts = function(userAccount, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_insertAccounts(userAccount);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_insertAccounts(userAccount);
  }
};

UserAccountServiceClient.prototype.send_insertAccounts = function(userAccount) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('insertAccounts', Thrift.MessageType.CALL, this.seqid());
  var params = {
    userAccount: userAccount
  };
  var args = new UserAccountService_insertAccounts_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

UserAccountServiceClient.prototype.recv_insertAccounts = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new UserAccountService_insertAccounts_result();
  result.read(input);
  input.readMessageEnd();

  callback(null);
};
var UserAccountServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
UserAccountServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
UserAccountServiceProcessor.prototype.process_getAccounts = function(seqid, input, output) {
  var args = new UserAccountService_getAccounts_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getAccounts.length === 0) {
    Q.fcall(this._handler.getAccounts.bind(this._handler))
      .then(function(result) {
        var result_obj = new UserAccountService_getAccounts_result({success: result});
        output.writeMessageBegin("getAccounts", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getAccounts", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getAccounts(function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new UserAccountService_getAccounts_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("getAccounts", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getAccounts", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
UserAccountServiceProcessor.prototype.process_insertAccounts = function(seqid, input, output) {
  var args = new UserAccountService_insertAccounts_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.insertAccounts.length === 1) {
    Q.fcall(this._handler.insertAccounts.bind(this._handler), args.userAccount)
      .then(function(result) {
        var result_obj = new UserAccountService_insertAccounts_result({success: result});
        output.writeMessageBegin("insertAccounts", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("insertAccounts", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.insertAccounts(args.userAccount, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new UserAccountService_insertAccounts_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("insertAccounts", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("insertAccounts", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
